

build-job:
  stage: build
  script:
    - docker-compose up -d

build-job1: 
  stage: deployment #musste build sein will aber noch nicht testen solange keine stage umgebung vorhanden ist 
  script:
    - kubectl apply -f deployment.yml
